### ISSUE TITLE
RPCQ server does not respect `--protoquil` flag

### ISSUE THREAD

**Issue by ecpeterson** [rigetti/quilc#238]
When the RPCQ server is started with `--protoquil` present on the command line, it emits code as if the flag were absent. I suspect that this comes from a bad interaction between the RPCQ server's use of `bordeaux-threads`, which gives each thread its own dynamic context, and the recent merge of #212, which prefers dynamic binding to global state mutation. This specific bug would also be resolved by attending to #229, though by quite different means.

If we had more thorough testing of the application code, we would have caught this before merge.

**Comment by appleby** [comment]
Shucks! I explicitly left the global state in `web-server.lisp` alone to avoid confusing bordeaux-threads, but did not consider the interaction with the RPCQ server. Actually, this makes me think I've probably broken the http server as well since it also references `*protoquil*` and `*statistics-dictionary*`.

Perhaps bordeaux-threads' [`*default-special-bindings*`](https://trac.common-lisp.net/bordeaux-threads/wiki/ApiDocumentation#default-special-bindings) could provide relief until whatever solution is proposed in #229 can be implemented.

In the mean time, #212 could be reverted while I figure out how to unbreak things.
