### ISSUE TITLE
BUILD-GATE will accept single-float parameters, but PRINT-INSTRUCTION will raise a cryptic error if parameters are not DOUBLE-FLOAT.

### ISSUE THREAD

**Issue by notmgsk** [rigetti/quilc#434]
e.g.

```
(build-gate "RX" (list 0.4) 0) ;; change 0.4 to 0.4d0 
```

> There is no applicable method for the generic function
>    #<STANDARD-GENERIC-FUNCTION CL-QUIL::PRINT-INSTRUCTION-GENERIC (31)>
> when called with arguments
>   (0 #<SB-IMPL::STRING-OUTPUT-STREAM {10036FA803}>).

**Comment by appleby** [comment]
Tangentially related: #313

**Comment by rigettizach** [comment]
I thought this might be a simple matter of updating `%capture-param` to make any number a constant, but that blows up later on the test from #313: 

    (quil::print-parsed-program
     (quil:compiler-hook (quil:parse-quil "RX(i) 0")
                         (quil::build-nq-linear-chip 2)))

    A violent error occurred when compressing a subsequence.
    The offending subsequence is:
    RZ(1.5707963267948966) 0
    RX(1.5707963267948966) 0
    RZ(1.0i) 0
    RX(-1.5707963267948966) 0
    RZ(-1.5707963267948966) 0
    The current compression context is:
    #S(COMPILATION-CONTEXT :AQVM #S(ANTISOCIAL-QVM :WFS #(NOT-SIMULATED NOT-SIMULATED) :INTERNAL-INDICES #(NOT-SIMULATED NOT-SIMULATED)) :CHIP-SPECIFICATION #<CHIP-SPECIFICATION of 2:1 objects>)

The debugger has this:

    The value
      #C(-0.0d0 -0.5d0)
    is not of type
      REAL

The stack looks like:

    (CIS #C(-0.0d0 -0.5d0))

What *should* happen here instead?

**Comment by appleby** [comment]
Based on @stylewarning's last comment in #313, it seems like there was consensus that restricting gate parameters to `real` and just raising a clearer error for complex values was reasonable.

For other numeric types, I guess we could either coerce to `double-float`, or else raise a more helpful error. Not sure which is preferable. Coercing seems more convenient for REPL hacking, raising an error "safer" in the sense of avoiding rounding errors in the coercion (no clue if those are significant enough to matter). Pretty sure this only affects explicit calls to `build-gate` by the programmer, since the quil parser automatically parses float parameters as `double-float`.

I guess my vote would be to `error` for `complex` and maybe `cerror` for `real`. Something like:

``` diff
diff --git a/src/build-gate.lisp b/src/build-gate.lisp
index f8ad3ee1..636bfa45 100644
--- a/src/build-gate.lisp
+++ b/src/build-gate.lisp
@@ -25,6 +25,11 @@
   (typecase param
     (double-float
      (constant param))
+    (real
+     (cerror "coerce to DOUBLE-FLOAT" "Gate params must be DOUBLE-FLOATs, not ~A" (type-of param))
+     (constant (coerce param 'double-float)))
+    (complex
+     (error "verboten"))
     (memory-ref
      (make-delayed-expression nil nil param))
     (otherwise
```

There are some comments by ecp in #313 that mention Quilt maybe wanting complex-valued params. Worth getting @kilimanjaro's opinion on whether this change to `%capture-param` would cause problems for Quilt.
