### ISSUE TITLE
Elide DEFCIRCUITs in compiled output at the command line

### ISSUE THREAD

**Issue by stylewarning** [rigetti/quilc#540]
At the command line only!

After compiling a program, circuits will have been expanded completely. We shouldn't print those. (However, in implementing this improvement, we don't want to strip out the circuit definitions too early! Only at the command line right before the program is printed to stdout.)

This "issue" comes up when compiling QASM circuits.

**Comment by notmgsk** [comment]
Does `print-parsed-program` really ever need to print circuits? I suppose that could be restricted to: should it print circuits if it has undergone the `expand-circuits` transform?

**Comment by ecpeterson** [comment]
@stylewarning and I talked about this a little bit, but we didn't record our thoughts. My feeling today is that `expand-circuits` should actually eliminate `DEFCIRCUIT` definitions as well as doing the expansion. We decided not to do this at the time because we weren't sure how this would interact with name resolution, this budding "environment" / "environs" object, and so on. Now, with  "environs" scrubbed from the code, I don't see what the hang-up is anymore.
