### ISSUE TITLE
Error while checking quilc --version

### ISSUE THREAD

**Issue by akshat-suwalka** [rigetti/quilc#634]
I had installed GNU/LINUX(deb) in UBUNTU 16.04 LTS by help of this link :
https://qcs.rigetti.com/sdk-downloads

After following the steps given here:
http://docs.rigetti.com/en/stable/start.html#server

The quilc installed but when i runned the code "quilc --version" , the following error had came:

Unhandled SIMPLE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                    {10006804F3}>:
  Error opening shared object "libssl.so.1.1":
  libssl.so.1.1: cannot open shared object file: No such file or directory.

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {10006804F3}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<SIMPLE-ERROR "Error opening ~:[runtime~;shared object ~:*~S~]:
  ~A." {1000E3D7B3}> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK *INVOKE-DEBUGGER-HOOK* #<SIMPLE-ERROR "Error opening ~:[runtime~;shared object ~:*~S~]:
  ~A." {1000E3D7B3}>)
2: (INVOKE-DEBUGGER #<SIMPLE-ERROR "Error opening ~:[runtime~;shared object ~:*~S~]:
  ~A." {1000E3D7B3}>)
3: (ERROR "Error opening ~:[runtime~;shared object ~:*~S~]:
  ~A." "libssl.so.1.1" "libssl.so.1.1: cannot open shared object file: No such file or directory")
4: (SB-SYS:DLOPEN-OR-LOSE #S(SB-ALIEN::SHARED-OBJECT :PATHNAME #P"libssl.so.1.1" :NAMESTRING "libssl.so.1.1" :HANDLE NIL :DONT-SAVE NIL))
5: (SB-ALIEN::TRY-REOPEN-SHARED-OBJECT #S(SB-ALIEN::SHARED-OBJECT :PATHNAME #P"libssl.so.1.1" :NAMESTRING "libssl.so.1.1" :HANDLE NIL :DONT-SAVE NIL))
6: (SB-SYS:REOPEN-SHARED-OBJECTS)
7: (SB-IMPL::FOREIGN-REINIT)
8: (SB-IMPL::REINIT)
9: ((FLET SB-UNIX::BODY :IN SAVE-LISP-AND-DIE))
10: ((FLET "WITHOUT-INTERRUPTS-BODY-14" :IN SAVE-LISP-AND-DIE))
11: ((LABELS SB-IMPL::RESTART-LISP :IN SAVE-LISP-AND-DIE))

unhandled condition in --disable-debugger mode, quitting

Please help to resolve in it!

I had read the issue : https://github.com/rigetti/quilc/issues/417
But it tell to install it from the link: https://downloads.rigetti.com/qcs-sdk/forest-sdk-linux-deb.tar.bz2
that i had done but the same problem came.

@notmgsk

**Comment by notmgsk** [comment]
Thanks for reporting this. I'll take a look as soon as I can.

**Comment by notmgsk** [comment]
@akshat-suwalka Can you try again with http://downloads.rigetti.com/qcs-sdk/forest-sdk-2.19.1-linux-deb.tar.bz2

**Comment by akshat-suwalka** [comment]
@notmgsk Thank you so much Big B!

**Comment by akshat-suwalka** [comment]
@notmgsk Can you give some explanation why earlier it doesn't work and now in this new version it is working and what changes did you make to correct it?

**Comment by notmgsk** [comment]
@akshat-suwalka I can try, though I don't know how helpful it will be.

Our `Makefile` has two interesting targets: `make quilc` and `make quilc-sdk`. The latter is like the former except that it disables some features in the compiler. In your case, it disables any dependencies on SSL. When we build and package quilc (and qvm) for the Forest SDK, we use `make quilc-sdk` because we don't want to introduce a libssl dependency for the user (you). However, I made a mistake in a previous commit to quilc that effectively meant that I was building and packaging the `make quilc` variant, and thus unintentionally introducing a libssl dependency.

You can see the fix here: https://github.com/rigetti/quilc/pull/636/files

Not sure how helpful that was. :)
